package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
/**
 * Aerolinea generated by hbm2java
 */
public class Aerolinea  implements java.io.Serializable {


     private Integer pkIdAerolinea;
     private String nombre;
     private int idPais;
     private String ultimoUsuario;
     private Date ultimaFecha;
     private Pais pais;

    public Aerolinea() {
    }

	
    public Aerolinea(String nombre, int idPais) {
        this.nombre = nombre;
        this.idPais=idPais;
        this.pais=null;
    }
    public Aerolinea(String nombre, int idPais,String ultimoUsuario, Date ultimaFecha) {
       this.nombre = nombre;
       this.idPais=idPais;
       this.ultimoUsuario = ultimoUsuario;
       this.ultimaFecha = ultimaFecha;
       this.pais=null;
    }

    public Pais getPais() {
        return pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }
   
    public Integer getPkIdAerolinea() {
        return this.pkIdAerolinea;
    }
    
    public void setPkIdAerolinea(Integer pkIdAerolinea) {
        this.pkIdAerolinea = pkIdAerolinea;
    }
    public String getNombre() {
        return this.nombre;
    }

    public int getIdPais() {
        return idPais;
    }

    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
}