package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private int idAvion;
     private int aerolinea;
     private int ruta;
     private int tipoAvion;
     private Date horario;
     private String ultimoUsuario;
     private Date ultimaFecha;
     private Ruta rutao;
     private TipoAvion tipoAviono;
   
     public Avion() {
    }

	
    public Avion(int idAvion, int aerolinea, int ruta, int tipoAvion, Date horario) {
        this.idAvion = idAvion;
        this.aerolinea = aerolinea;
        this.ruta = ruta;
        this.tipoAvion = tipoAvion;
        this.horario = horario;
        this.rutao=null;
        this.tipoAviono=null;
    }
    public Avion(int idAvion, int aerolinea, int ruta, int tipoAvion, Date horario, String ultimoUsuario, Date ultimaFecha) {
       this.idAvion = idAvion;
       this.aerolinea = aerolinea;
       this.ruta = ruta;
       this.tipoAvion = tipoAvion;
       this.horario = horario;
       this.ultimoUsuario = ultimoUsuario;
       this.ultimaFecha = ultimaFecha;
       this.rutao=null;
       this.tipoAviono=null;
    }

    public Ruta getRutao() {
        return rutao;
    }

    public void setRutao(Ruta rutao) {
        this.rutao = rutao;
    }

    public TipoAvion getTipoAviono() {
        return tipoAviono;
    }

    public void setTipoAviono(TipoAvion tipoAviono) {
        this.tipoAviono = tipoAviono;
    }
   
    
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }
    public int getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(int aerolinea) {
        this.aerolinea = aerolinea;
    }
    public int getRuta() {
        return this.ruta;
    }
    
    public void setRuta(int ruta) {
        this.ruta = ruta;
    }
    public int getTipoAvion() {
        return this.tipoAvion;
    }
    
    public void setTipoAvion(int tipoAvion) {
        this.tipoAvion = tipoAvion;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
}