package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private int idAvion;
     private int aerolinea;
     private int ruta;
     private int tipoAvion;
     private Date horarioSalida;
     private String ultimoUsuario;
     private Date ultimaFecha;
     private Ruta rutao;
     private TipoAvion tipoAviono;
     private Aerolinea aerolineao;
     private Date horarioLlegada;
     
     public Avion() {
    }

	
    public Avion(int idAvion, int aerolinea, int ruta, int tipoAvion, Date horarioSalida, Date horarioLlegada) {
        this.idAvion = idAvion;
        this.aerolinea = aerolinea;
        this.ruta = ruta;
        this.tipoAvion = tipoAvion;
        this.horarioSalida = horarioSalida;
        this.horarioLlegada=horarioLlegada;
        this.rutao=null;
        this.tipoAviono=null;
        this.aerolineao=null;
    }
    public Avion(int idAvion, int aerolinea, int ruta, int tipoAvion, Date horarioSalida, Date horarioLlegada, String ultimoUsuario, Date ultimaFecha) {
       this.idAvion = idAvion;
       this.aerolinea = aerolinea;
       this.ruta = ruta;
       this.tipoAvion = tipoAvion;
       this.horarioSalida = horarioSalida;
       this.ultimoUsuario = ultimoUsuario;
       this.ultimaFecha = ultimaFecha;
       this.horarioLlegada=horarioLlegada;
       this.rutao=null;
       this.tipoAviono=null;
       this.aerolineao=null;
    }

    public Aerolinea getAerolineao() {
        return aerolineao;
    }

    public void setAerolineao(Aerolinea aerolineao) {
        this.aerolineao = aerolineao;
    }

    
    public Date getHorarioLlegada() {
        return horarioLlegada;
    }

    public void setHorarioLlegada(Date horarioLlegada) {
        this.horarioLlegada = horarioLlegada;
    }

    public Ruta getRutao() {
        return rutao;
    }

    public void setRutao(Ruta rutao) {
        this.rutao = rutao;
    }

    public TipoAvion getTipoAviono() {
        return tipoAviono;
    }

    public void setTipoAviono(TipoAvion tipoAviono) {
        this.tipoAviono = tipoAviono;
    }
   
    
    public int getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(int idAvion) {
        this.idAvion = idAvion;
    }
    public int getAerolinea() {
        return this.aerolinea;
    }
    
    public void setAerolinea(int aerolinea) {
        this.aerolinea = aerolinea;
    }
    public int getRuta() {
        return this.ruta;
    }
    
    public void setRuta(int ruta) {
        this.ruta = ruta;
    }
    public int getTipoAvion() {
        return this.tipoAvion;
    }
    
    public void setTipoAvion(int tipoAvion) {
        this.tipoAvion = tipoAvion;
    }
    public Date getHorarioSalida() {
        return this.horarioSalida;
    }
    
    public void setHorarioSalida(Date horarioSalida) {
        this.horarioSalida = horarioSalida;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
}