package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1



/**
 * BoletoId generated by hbm2java
 */
public class BoletoId  implements java.io.Serializable {


     private int idHorario;
     private int idUsuario;

    public BoletoId() {
    }

    public BoletoId(int idHorario, int idUsuario) {
       this.idHorario = idHorario;
       this.idUsuario = idUsuario;
    }
   
    public int getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BoletoId) ) return false;
		 BoletoId castOther = ( BoletoId ) other; 
         
		 return (this.getIdHorario()==castOther.getIdHorario())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHorario();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


