package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private BoletoId id;
     private Horario horario;
     private Usuario usuario;
     private Integer consecutivo;
     private int numAsiento;
     private int numFila;
     private Date fechaCompra;

    public Boleto() {
    }

	
    public Boleto(BoletoId id, Horario horario, Usuario usuario, int numAsiento, int numFila) {
        this.id = id;
        this.horario = horario;
        this.usuario = usuario;
        this.numAsiento = numAsiento;
        this.numFila = numFila;
    }
    public Boleto(BoletoId id, Horario horario, Usuario usuario, Integer consecutivo, int numAsiento, int numFila, Date fechaCompra) {
       this.id = id;
       this.horario = horario;
       this.usuario = usuario;
       this.consecutivo = consecutivo;
       this.numAsiento = numAsiento;
       this.numFila = numFila;
       this.fechaCompra = fechaCompra;
    }
   
    public BoletoId getId() {
        return this.id;
    }
    
    public void setId(BoletoId id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public int getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(int numAsiento) {
        this.numAsiento = numAsiento;
    }
    public int getNumFila() {
        return this.numFila;
    }
    
    public void setNumFila(int numFila) {
        this.numFila = numFila;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }




}


