package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private Avion avion;
     private Date horaLlegada;
     private float precio;
     private Set<Boleto> boletos = new HashSet<Boleto>(0);

    public Horario() {
    }

	
    public Horario(Date horaLlegada, float precio) {
        this.horaLlegada = horaLlegada;
        this.precio = precio;
    }
    public Horario(Avion avion, Date horaLlegada, float precio, Set<Boleto> boletos) {
       this.avion = avion;
       this.horaLlegada = horaLlegada;
       this.precio = precio;
       this.boletos = boletos;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set<Boleto> getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set<Boleto> boletos) {
        this.boletos = boletos;
    }




}


