package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1



/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private String iso;
     private String nombre;

    public Pais() {
    }

	
    public Pais(String iso) {
        this.iso = iso;
    }
    public Pais(String iso, String nombre) {
       this.iso = iso;
       this.nombre = nombre;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getIso() {
        return this.iso;
    }
    
    public void setIso(String iso) {
        this.iso = iso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}