package cr.ac.una.prograiv.project.domain;
// Generated 31/05/2017 07:47:08 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TipoAvion generated by hbm2java
 */
public class TipoAvion  implements java.io.Serializable {


     private Integer idTipo;
     private String modelo;
     private String marca;
     private int año;
     private int cantPasajeros;
     private int cantFila;
     private int cantAsientosPorFila;
     private String ultimoUsuario;
     private Date ultimaFecha;

    public TipoAvion() {
    }

	
    public TipoAvion(String modelo, String marca, int año, int cantFila, int cantAsientosPorFila) {
        this.modelo = modelo;
        this.marca = marca;
        this.año = año;
        this.cantPasajeros = cantFila*cantAsientosPorFila;
        this.cantFila = cantFila;
        this.cantAsientosPorFila = cantAsientosPorFila;
    }
    public TipoAvion(String modelo, String marca, int año, int cantPasajeros, int cantFila, int cantAsientosPorFila, String ultimoUsuario, Date ultimaFecha) {
       this.modelo = modelo;
       this.marca = marca;
       this.año = año;
       this.cantPasajeros = cantPasajeros;
       this.cantFila = cantFila;
       this.cantAsientosPorFila = cantAsientosPorFila;
       this.ultimoUsuario = ultimoUsuario;
       this.ultimaFecha = ultimaFecha;
    }
   
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getAño() {
        return this.año;
    }
    
    public void setAño(int año) {
        this.año = año;
    }
    public int getCantPasajeros() {
        return this.cantPasajeros;
    }
    
    public void setCantPasajeros(int cantPasajeros) {
        this.cantPasajeros = cantPasajeros;
    }
    public int getCantFila() {
        return this.cantFila;
    }
    
    public void setCantFila(int cantFila) {
        this.cantFila = cantFila;
    }
    public int getCantAsientosPorFila() {
        return this.cantAsientosPorFila;
    }
    
    public void setCantAsientosPorFila(int cantAsientosPorFila) {
        this.cantAsientosPorFila = cantAsientosPorFila;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
}


